services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      LANDSCAPE_ASSISTANT_DATABASE_PASSWORD: ${LANDSCAPE_ASSISTANT_DATABASE_PASSWORD}
      LANDSCAPE_ASSISTANT_DATABASE_USER: ${LANDSCAPE_ASSISTANT_DATABASE_USER}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      OPEN_AI_ASSISTANT_ID: ${OPEN_AI_ASSISTANT_ID}
      ECOWITT_API_KEY: ${ECOWITT_API_KEY}
      ECOWITT_APPLICATION_KEY: ${ECOWITT_APPLICATION_KEY}
      ECOWITT_MAC_ADDRESS: ${ECOWITT_MAC_ADDRESS}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      TOMORROW_IO_API_KEY: ${TOMORROW_IO_API_KEY}
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379

  postgres:
    image: postgres:16.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${LANDSCAPE_ASSISTANT_DATABASE_USER}
      POSTGRES_PASSWORD: ${LANDSCAPE_ASSISTANT_DATABASE_PASSWORD}
    ports:
      - 5432:5432

volumes:
  redis-data:
  postgres-data:
